AWSTemplateFormatVersion: 2010-09-09

Parameters:

  AMI:
    Type: String
    Default: ami-0149b2da6ceec4bb0
    Description: The Windows AMI to use.

  KeyPair:
    Description: Which Key Pair would you like to use for remote access?
    Type: 'AWS::EC2::KeyPair::KeyName'
    Default: 'deploy'

Resources:

  InstanceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: For ssh on port 22 access and 8080 port access for Customer App
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "8080"
          ToPort: "8080"
          CidrIp: 0.0.0.0/0

  Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: ReactApp
      ImageId: !Ref AMI # ImageId depends on a region. The current image is valid ONLY in US-EAST-1
      KeyName: !Ref KeyPair # Your pem key name
      SecurityGroups:
        - !Ref InstanceSG
      UserData: !Base64
        Fn::Sub: |
          #!/bin/bash
          sudo apt update
          sudo apt install ansible -y
  
